version: '3'
services:
  database:
    image: "postgres:9.6"
    volumes:
      - db_data:/var/lib/postgresql/data/db
    environment:
      PGDATA: /var/lib/postgresql/data/psql
      POSTGRES_DB: root
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    expose:
      - 5432
volumes:
  db_data:
